site_name: Chispa
edit_uri: edit/main/docs/
repo_name: MrPowers/chispa
repo_url: https://github.com/MrPowers/chispa
site_url: https://mrpowers.github.io/chispa/
site_description: PySpark test helper methods with beautiful error messages.
site_author: Matthew Powers
copyright: Maintained by <a href="https://github.com/MrPowers">Matthew</a>.

nav:
  - Home: index.md
  - API Docs: reference/SUMMARY.md

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              show_if_no_docstring: true
            show_source: true

theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MrPowers/chispa
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/chispa/

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - markdown_include.include:
      base_path: .
