name: "setup-poetry-env"
description: "Composite action to setup the Python and poetry environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "3.11"
  pyspark-version:
    required: false
    description: "The pyspark version to use"
    default: "3.5.1"
  with-docs:
    required: false
    description: "Install the docs dependency group"
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      env:
        # renovate: datasource=pypi depName=poetry
        POETRY_VERSION: "1.8.3"
      run: curl -sSL https://install.python-poetry.org | python - -y
      shell: bash

    - name: Add Poetry to Path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Configure Poetry virtual environment in project
      run: poetry config virtualenvs.in-project true
      shell: bash

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.pyspark-version }}-${{ inputs.with-docs }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        if [[ "${{ inputs.with-docs }}" == "true" ]]; then
          poetry install --no-interaction --with mkdocs
        else
          poetry install --no-interaction
        fi
        poetry run pip install pyspark==${{ inputs.pyspark-version }}
      shell: bash
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

    - name: Print python and pyspark version
      run: |
        poetry run python --version
        poetry run pyspark --version
      shell: bash
